version: '3.9'

services:
  qdrant:
    container_name: steam-database
    image: qdrant/qdrant
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant-data:/qdrant/storage:z

volumes:
  qdrant-data:
